//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiUsingDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StdId { get; set; }
        public string StdName { get; set; }
        public int StdAge { get; set; }
        public string StdClass { get; set; }
        public int TeacherId { get; set; }
        public string Gender { get; set; }
    }
}
